### ISSUE TITLE
Material Design guidelines

### ISSUE THREAD

**Issue by bizhong** [bizhong/bizhong.github.io#1]
学习 [Material Design](https://material.io/guidelines/)，自己整理的一些规范：

```css
html {
  font-size: 16px;
}

:root {
  /* Elevation 海拔 */
  --elevation-1dp: 1; /* Switch */
  --elevation-2dp: 2; /* Card (resting elevation), Raised button (resting elevation), Quick entry / Search bar (resting elevation) */
  --elevation-3dp: 3; /* Refresh indicator, Quick entry / Search bar (scrolled state) */
  --elevation-4dp: 4; /* App Bar */
  --elevation-6dp: 6; /* Floating action button (FAB - resting elevation), Snackbar */
  --elevation-8dp: 8; /* Bottom navigation bar, Menu, Card (when picked up), Raised button (pressed state) */
  --elevation-9dp: 9; /* Sub menu (+1dp for each sub menu) */
  --elevation-12dp: 12; /* Floating action button (FAB - pressed) */
  --elevation-16dp: 16; /* Nav drawer, Right drawer, Modal bottom Sheet */
  --elevation-24dp: 24; /* Dialog, Picker */


  /* Shadows 阴影 */
  --shadow-1dp: 0 0 2px 0 rgba(0, 0, 0, .14), 0 2px 2px 0 rgba(0, 0, 0, .12), 0 1px 3px 0 rgba(0, 0, 0, .2);
  --shadow-2dp: 0 0 4px 0 rgba(0, 0, 0, .14), 0 3px 4px 0 rgba(0, 0, 0, .12), 0 1px 5px 0 rgba(0, 0, 0, .2);
  --shadow-3dp: 0 3px 3px 0 rgba(0, 0, 0, .14), 0 3px 4px 0 rgba(0, 0, 0, .12), 0 1px 8px 0 rgba(0, 0, 0, .2);
  --shadow-4dp: 0 2px 4px 0 rgba(0, 0, 0, .14), 0 4px 5px 0 rgba(0, 0, 0, .12), 0 1px 10px 0 rgba(0, 0, 0, .2);
  --shadow-6dp: 0 6px 10px 0 rgba(0, 0, 0, .14), 0 1px 18px 0 rgba(0, 0, 0, .12), 0 3px 5px 0 rgba(0, 0, 0, .2);
  --shadow-8dp: 0 8px 10px 1px rgba(0, 0, 0, .14), 0 3px 14px 3px rgba(0, 0, 0, .12), 0 4px 15px 0 rgba(0, 0, 0, .2);
  --shadow-9dp: 0 9px 12px 1px rgba(0, 0, 0, .14), 0 3px 16px 2px rgba(0, 0, 0, .12), 0 5px 6px 0 rgba(0, 0, 0, .2);
  --shadow-12dp: 0 12px 17px 2px rgba(0, 0, 0, .14), 0 5px 22px 4px rgba(0, 0, 0, .12), 0 7px 8px 0 rgba(0, 0, 0, .2);
  --shadow-16dp: 0 16px 24px 2px rgba(0, 0, 0, .14), 0 6px 30px 5px rgba(0, 0, 0, .12), 0 8px 10px 0 rgba(0, 0, 0, .2);
  --shadow-24dp: 0 24px 38px 3px rgba(0, 0, 0, .14), 0 9px 46px 8px rgba(0, 0, 0, .12), 0 11px 15px 0 rgba(0, 0, 0, .2);


  /* Duration 持续时间 */
  /* Mobile 移动设备 */
  --duration-mobile-375ms: 375ms; /* 大型的、复杂的、全屏的元素 */
  --duration-mobile-225ms: 225ms; /* 进入屏幕的元素 */
  --duration-mobile-195ms: 195ms; /* 离开屏幕的元素 */
  /* Tablets 平板电脑 */
  --duration-tablets-375ms: 485ms; /* 大型的、复杂的、全屏的元素，375ms * (1 + 30%) = 487.5ms */
  --duration-tablets-225ms: 295ms; /* 进入屏幕的元素，225ms * (1 + 30%) = 292.5ms */
  --duration-tablets-195ms: 255ms; /* 离开屏幕的元素，195ms * (1 + 30%) = 253.5ms */
  /* Wearables 可穿戴式设备 */
  --duration-wearables-375ms: 265ms; /* 大型的、复杂的、全屏的元素，375ms * (1 - 30%) = 262.5ms */
  --duration-wearables-225ms: 155ms; /* 进入屏幕的元素，225ms * (1 - 30%) = 157.5ms */
  --duration-wearables-195ms: 135ms; /* 离开屏幕的元素，195ms * (1 - 30%) = 136.5ms */
  /* Desktop 桌面 */
  --duration-desktop-375ms: 195ms; /* 大型的、复杂的、全屏的元素，150ms ~ 200ms */
  --duration-desktop-225ms: 175ms; /* 进入屏幕的元素 */
  --duration-desktop-195ms: 155ms; /* 离开屏幕的元素 */


  /* Easing curves 缓和曲线 */
  /* Standard curve 标准曲线 */
  --easing-standard-curve: cubic-bezier(.4, 0, .2, 1); /* 屏幕上的移动（弧向上、弧向下、沿水平或垂直单轴移动的元素），进出屏幕移动（相对运动，移动设备 300ms 以上） */
  /* Deceleration curve 减速曲线 */
  --easing-deceleration-curve: cubic-bezier(0, 0, .2, 1); /* 进出屏幕移动（独立运动 - 进入屏幕，移动设备 225ms 以上） */
  /* Acceleration curve 加速曲线 */
  --easing-acceleration-curve: cubic-bezier(.4, 0, 1, 1); /* 进出屏幕移动（独立运动 - 永久离开屏幕，移动设备 195ms 以上） */
  /* Sharp curve 急弯曲线，锐曲线 */
  --easing-sharp-curve: cubic-bezier(.4, 0, .6, 1); /* 进出屏幕移动（独立运动 - 暂时离开屏幕，移动设备 300ms 以上） */


  /* Color 颜色 */
  /* Red 红色 */
  --color-red-50: #ffebee;
  --color-red-100: #ffcdd2;
  --color-red-200: #ef9a9a;
  --color-red-300: #e57373;
  --color-red-400: #ef5350;
  --color-red-500: #f44336;
  --color-red-600: #e53935;
  --color-red-700: #d32f2f;
  --color-red-800: #c62828;
  --color-red-900: #b71c1c;
  --color-red-a100: #ff8a80;
  --color-red-a200: #ff5252;
  --color-red-a400: #ff1744;
  --color-red-a700: #d50000;
  /* Pink 粉红色 */
  --color-pink-50: #fce4ec;
  --color-pink-100: #f8bbd0;
  --color-pink-200: #f48fb1;
  --color-pink-300: #f06292;
  --color-pink-400: #ec407a;
  --color-pink-500: #e91e63;
  --color-pink-600: #d81b60;
  --color-pink-700: #c2185b;
  --color-pink-800: #ad1457;
  --color-pink-900: #880e4f;
  --color-pink-a100: #ff80ab;
  --color-pink-a200: #ff4081;
  --color-pink-a400: #f50057;
  --color-pink-a700: #c51162;
  /* Purple 紫色 */
  --color-purple-50: #f3e5f5;
  --color-purple-100: #e1bee7;
  --color-purple-200: #ce93d8;
  --color-purple-300: #ba68c8;
  --color-purple-400: #ab47bc;
  --color-purple-500: #9c27b0;
  --color-purple-600: #8e24aa;
  --color-purple-700: #7b1fa2;
  --color-purple-800: #6a1b9a;
  --color-purple-900: #4a148c;
  --color-purple-a100: #ea80fc;
  --color-purple-a200: #e040fb;
  --color-purple-a400: #d500f9;
  --color-purple-a700: #aa00ff;
  /* Deep Purple 深紫色 */
  --color-deep-purple-50: #ede7f6;
  --color-deep-purple-100: #d1c4e9;
  --color-deep-purple-200: #b39ddb;
  --color-deep-purple-300: #9575cd;
  --color-deep-purple-400: #7e57c2;
  --color-deep-purple-500: #673ab7;
  --color-deep-purple-600: #5e35b1;
  --color-deep-purple-700: #512da8;
  --color-deep-purple-800: #4527a0;
  --color-deep-purple-900: #311b92;
  --color-deep-purple-a100: #b388ff;
  --color-deep-purple-a200: #7c4dff;
  --color-deep-purple-a400: #651fff;
  --color-deep-purple-a700: #6200ea;
  /* Indigo 靛青色 */
  --color-indigo-50: #e8eaf6;
  --color-indigo-100: #c5cae9;
  --color-indigo-200: #9fa8da;
  --color-indigo-300: #7986cb;
  --color-indigo-400: #5c6bc0;
  --color-indigo-500: #3f51b5;
  --color-indigo-600: #3949ab;
  --color-indigo-700: #303f9f;
  --color-indigo-800: #283593;
  --color-indigo-900: #1a237e;
  --color-indigo-a100: #8c9eff;
  --color-indigo-a200: #536dfe;
  --color-indigo-a400: #3d5afe;
  --color-indigo-a700: #304ffe;
  /* Blue 蓝色 */
  --color-blue-50: #e3f2fd;
  --color-blue-100: #bbdefb;
  --color-blue-200: #90caf9;
  --color-blue-300: #64b5f6;
  --color-blue-400: #42a5f5;
  --color-blue-500: #2196f3;
  --color-blue-600: #1e88e5;
  --color-blue-700: #1976d2;
  --color-blue-800: #1565c0;
  --color-blue-900: #0d47a1;
  --color-blue-a100: #82b1ff;
  --color-blue-a200: #448aff;
  --color-blue-a400: #2979ff;
  --color-blue-a700: #2962ff;
  /* Light Blue 浅蓝色 */
  --color-light-blue-50: #e1f5fe;
  --color-light-blue-100: #b3e5fc;
  --color-light-blue-200: #81d4fa;
  --color-light-blue-300: #4fc3f7;
  --color-light-blue-400: #29b6f6;
  --color-light-blue-500: #03a9f4;
  --color-light-blue-600: #039be5;
  --color-light-blue-700: #0288d1;
  --color-light-blue-800: #0277bd;
  --color-light-blue-900: #01579b;
  --color-light-blue-a100: #80d8ff;
  --color-light-blue-a200: #40c4ff;
  --color-light-blue-a400: #00b0ff;
  --color-light-blue-a700: #0091ea;
  /* Cyan 青色 */
  --color-cyan-50: #e0f7fa;
  --color-cyan-100: #b2ebf2;
  --color-cyan-200: #80deea;
  --color-cyan-300: #4dd0e1;
  --color-cyan-400: #26c6da;
  --color-cyan-500: #00bcd4;
  --color-cyan-600: #00acc1;
  --color-cyan-700: #0097a7;
  --color-cyan-800: #00838f;
  --color-cyan-900: #006064;
  --color-cyan-a100: #84ffff;
  --color-cyan-a200: #18ffff;
  --color-cyan-a400: #00e5ff;
  --color-cyan-a700: #00b8d4;
  /* Teal 蒂尔 */
  --color-teal-50: #e0f2f1;
  --color-teal-100: #b2dfdb;
  --color-teal-200: #80cbc4;
  --color-teal-300: #4db6ac;
  --color-teal-400: #26a69a;
  --color-teal-500: #009688;
  --color-teal-600: #00897b;
  --color-teal-700: #00796b;
  --color-teal-800: #00695c;
  --color-teal-900: #004d40;
  --color-teal-a100: #a7ffeb;
  --color-teal-a200: #64ffda;
  --color-teal-a400: #1de9b6;
  --color-teal-a700: #00bfa5;
  /* Green 绿色 */
  --color-green-50: #e8f5e9;
  --color-green-100: #c8e6c9;
  --color-green-200: #a5d6a7;
  --color-green-300: #81c784;
  --color-green-400: #66bb6a;
  --color-green-500: #4caf50;
  --color-green-600: #43a047;
  --color-green-700: #388e3c;
  --color-green-800: #2e7d32;
  --color-green-900: #1b5e20;
  --color-green-a100: #b9f6ca;
  --color-green-a200: #69f0ae;
  --color-green-a400: #00e676;
  --color-green-a700: #00c853;
  /* Light Green 淡绿色 */
  --color-light-green-50: #f1f8e9;
  --color-light-green-100: #dcedc8;
  --color-light-green-200: #c5e1a5;
  --color-light-green-300: #aed581;
  --color-light-green-400: #9ccc65;
  --color-light-green-500: #8bc34a;
  --color-light-green-600: #7cb342;
  --color-light-green-700: #689f38;
  --color-light-green-800: #558b2f;
  --color-light-green-900: #33691e;
  --color-light-green-a100: #ccff90;
  --color-light-green-a200: #b2ff59;
  --color-light-green-a400: #76ff03;
  --color-light-green-a700: #64dd17;
  /* Lime 绿黄色（青柠色） */
  --color-lime-50: #f9fbe7;
  --color-lime-100: #f0f4c3;
  --color-lime-200: #e6ee9c;
  --color-lime-300: #dce775;
  --color-lime-400: #d4e157;
  --color-lime-500: #cddc39;
  --color-lime-600: #c0ca33;
  --color-lime-700: #afb42b;
  --color-lime-800: #9e9d24;
  --color-lime-900: #827717;
  --color-lime-a100: #f4ff81;
  --color-lime-a200: #eeff41;
  --color-lime-a400: #c6ff00;
  --color-lime-a700: #aeea00;
  /* Yellow 黄色 */
  --color-yellow-50: #fffde7;
  --color-yellow-100: #fff9c4;
  --color-yellow-200: #fff59d;
  --color-yellow-300: #fff176;
  --color-yellow-400: #ffee58;
  --color-yellow-500: #ffeb3b;
  --color-yellow-600: #fdd835;
  --color-yellow-700: #fbc02d;
  --color-yellow-800: #f9a825;
  --color-yellow-900: #f57f17;
  --color-yellow-a100: #ffff8d;
  --color-yellow-a200: #ffff00;
  --color-yellow-a400: #ffea00;
  --color-yellow-a700: #ffd600;
  /* Amber 琥珀色 */
  --color-amber-50: #fff8e1;
  --color-amber-100: #ffecb3;
  --color-amber-200: #ffe082;
  --color-amber-300: #ffd54f;
  --color-amber-400: #ffca28;
  --color-amber-500: #ffc107;
  --color-amber-600: #ffb300;
  --color-amber-700: #ffa000;
  --color-amber-800: #ff8f00;
  --color-amber-900: #ff6f00;
  --color-amber-a100: #ffe57f;
  --color-amber-a200: #ffd740;
  --color-amber-a400: #ffc400;
  --color-amber-a700: #ffab00;
  /* Orange 橙色 */
  --color-orange-50: #fff3e0;
  --color-orange-100: #ffe0b2;
  --color-orange-200: #ffcc80;
  --color-orange-300: #ffb74d;
  --color-orange-400: #ffa726;
  --color-orange-500: #ff9800;
  --color-orange-600: #fb8c00;
  --color-orange-700: #f57c00;
  --color-orange-800: #ef6c00;
  --color-orange-900: #e65100;
  --color-orange-a100: #ffd180;
  --color-orange-a200: #ffab40;
  --color-orange-a400: #ff9100;
  --color-orange-a700: #ff6d00;
  /* Deep Orange 深橙色 */
  --color-deep-orange-50: #fbe9e7;
  --color-deep-orange-100: #ffccbc;
  --color-deep-orange-200: #ffab91;
  --color-deep-orange-300: #ff8a65;
  --color-deep-orange-400: #ff7043;
  --color-deep-orange-500: #ff5722;
  --color-deep-orange-600: #f4511e;
  --color-deep-orange-700: #e64a19;
  --color-deep-orange-800: #d84315;
  --color-deep-orange-900: #bf360c;
  --color-deep-orange-a100: #ff9e80;
  --color-deep-orange-a200: #ff6e40;
  --color-deep-orange-a400: #ff3d00;
  --color-deep-orange-a700: #dd2c00;
  /* Brown 棕色 */
  --color-brown-50: #efebe9;
  --color-brown-100: #d7ccc8;
  --color-brown-200: #bcaaa4;
  --color-brown-300: #a1887f;
  --color-brown-400: #8d6e63;
  --color-brown-500: #795548;
  --color-brown-600: #6d4c41;
  --color-brown-700: #5d4037;
  --color-brown-800: #4e342e;
  --color-brown-900: #3e2723;
  /* Grey 灰色 */
  --color-grey-50: #fafafa;
  --color-grey-100: #f5f5f5;
  --color-grey-200: #eeeeee;
  --color-grey-300: #e0e0e0;
  --color-grey-400: #bdbdbd;
  --color-grey-500: #9e9e9e;
  --color-grey-600: #757575;
  --color-grey-700: #616161;
  --color-grey-800: #424242;
  --color-grey-900: #212121;
  /* Blue Grey 蓝灰色 */
  --color-blue-grey-50: #eceff1;
  --color-blue-grey-100: #cfd8dc;
  --color-blue-grey-200: #b0bec5;
  --color-blue-grey-300: #90a4ae;
  --color-blue-grey-400: #78909c;
  --color-blue-grey-500: #607d8b;
  --color-blue-grey-600: #546e7a;
  --color-blue-grey-700: #455a64;
  --color-blue-grey-800: #37474f;
  --color-blue-grey-900: #263238;
  /* Black 黑色 */
  --color-black: #000000;
  /* White 白色 */
  --color-white: #ffffff;


  /* Theme color */
  --primary-color: #3e50b4; /* 主色 在应用程序的屏幕和组件中显示频率最高的颜色 */
  --accent-color: #ff3f80; /* 强调色（次色 Secondary color） Buttons, floating action buttons, and button text; Text fields, cursors, and text selection; Progress bars; Selection controls, buttons, and sliders; Links; Headlines */

  /* Text color */
  /* Dark text on light backgrounds */
  --dark-text: #000000;
  --dark-primary-text: #212121; /* 主要文本 87% */
  --dark-secondary-text: #737373; /* 次要文本 54% */
  --dark-disabled-text: #9b9b9b; /* 禁用文本，提示文本（Hint text） 38% */
  --dark-divider-text: #dbdbdb; /* 分割线 12% */
  /* White text on dark backgrounds */
  --light-text: #ffffff;
  --light-primary-text: #ffffff; /* 主要文本 100% */
  --light-secondary-text: #fefefe; /* 次要文本 70% */
  --light-disabled-text: #fdfdfd; /* 禁用文本，提示文本（Hint text） 50% */
  --light-divider-text: #dcdcdc; /* 分割线 12% */

  /* Icons and other elements opacity */
  /* Dark icons */
  --dark-active-focused-icon-opacity: .87; /* 活跃、聚焦的图标 */
  --dark-active-unfocused-icon-opacity: .54; /* 活跃、未聚焦的图标 */
  --dark-inactive-icon-opacity: .38; /* 不活跃的图标 */
  /* Light icons */
  --light-active-focused-icon-opacity: 1; /* 活跃、聚焦的图标 */
  --light-active-unfocused-icon-opacity: .7; /* 活跃、未聚焦的图标 */
  --light-inactive-icon-opacity: .5; /* 不活跃的图标 */

  /* Theme background */
  /* Light theme */
  --light-statusbar-background: #e0e0e0; /* Status bar */
  --light-appbar-background: #f5f5f5; /* App bar */
  --light-content-background: #fafafa; /* Background */
  --light-card-background: #ffffff; /* Cards/Dialogs */
  /* Dark theme */
  --dark-statusbar-background: #000000; /* Status bar */
  --dark-appbar-background: #212121; /* App bar */
  --dark-content-background: #303030; /* Background */
  --dark-card-background: #424242; /* Cards/Dialogs */


  /* Typography */
  /* Typefaces */
  --typography-font-family: "Roboto", "Noto", sans-serif;

  /* Styles */
  /* English and English-like (Latin, Greek, and Cyrillic) */
  --typography-english-display4-font-size: 7rem; /* Type 112sp */
  --typography-english-display4-font-weight: 300; /* Weight Light */
  --typography-english-display4-line-height: 7rem; /* Leading 112dp */
  --typography-english-display4-letter-spacing: -.04em; /* Tracking -10 */
  --typography-english-display3-font-size: 3.5rem; /* Type 56sp */
  --typography-english-display3-font-weight: 400; /* Weight Regular */
  --typography-english-display3-line-height: 3.5rem; /* Leading 56dp */
  --typography-english-display3-letter-spacing: -.02em; /* Tracking -5 */
  --typography-english-display2-font-size: 2.8125rem; /* Type 45sp */
  --typography-english-display2-font-weight: 400; /* Weight Regular */
  --typography-english-display2-line-height: 3rem; /* Leading 48dp */
  --typography-english-display2-letter-spacing: normal; /* Tracking 0 */
  --typography-english-display1-font-size: 2.125rem; /* Type 34sp */
  --typography-english-display1-font-weight: 400; /* Weight Regular */
  --typography-english-display1-line-height: 2.5rem; /* Leading 40dp */
  --typography-english-display1-letter-spacing: normal; /* Tracking 0 */
  --typography-english-headline-font-size: 1.5rem; /* Type 24sp */
  --typography-english-headline-font-weight: 400; /* Weight Regular */
  --typography-english-headline-line-height: 2rem; /* Leading 32dp */
  --typography-english-headline-letter-spacing: normal; /* Tracking 0 */
  --typography-english-title-font-size: 1.25rem; /* Type 20sp */
  --typography-english-title-font-weight: 500; /* Weight Medium */
  --typography-english-title-line-height: 2rem; /* Leading 32dp */
  --typography-english-title-letter-spacing: .02em; /* Tracking 5 */
  --typography-english-subheading2-font-size: 1rem; /* Type 16sp (Device) and 15sp (Desktop) */
  --typography-english-subheading2-font-weight: 400; /* Weight Regular */
  --typography-english-subheading2-line-height: 1.75rem; /* Leading 28dp */
  --typography-english-subheading2-letter-spacing: .04em; /* Tracking 10 */
  --typography-english-subheading1-font-size: .938rem; /* Type 16sp (Device) and 15sp (Desktop) */
  --typography-english-subheading1-font-weight: 400; /* Weight Regular */
  --typography-english-subheading1-line-height: 1.5rem; /* Leading 24dp */
  --typography-english-subheading1-letter-spacing: .04em; /* Tracking 10 */
  --typography-english-body2-font-size: .875rem; /* Type 14sp (Device) and 13sp (Desktop) */
  --typography-english-body2-font-weight: 500; /* Weight Medium */
  --typography-english-body2-line-height: 1.5rem; /* Leading 24dp */
  --typography-english-body2-letter-spacing: .04em; /* Tracking 10 */
  --typography-english-body1-font-size: .875rem; /* Type 14sp (Device) and 13sp (Desktop) */
  --typography-english-body1-font-weight: 400; /* Weight Regular */
  --typography-english-body1-line-height: 1.25rem; /* Leading 20dp */
  --typography-english-body1-letter-spacing: .04em; /* Tracking 10 */
  --typography-english-caption-font-size: .75rem; /* Type 12sp */
  --typography-english-caption-font-weight: 400; /* Weight Regular */
  --typography-english-caption-line-height: 1.25rem; /* Leading 20dp */
  --typography-english-caption-letter-spacing: .08em; /* Tracking 20 */
  --typography-english-button-font-size: .875rem; /* Type (all caps) 14sp */
  --typography-english-button-font-weight: 500; /* Weight Medium */
  --typography-english-button-line-height: 2.25rem; /* Leading 36sp */
  --typography-english-button-letter-spacing: .04em; /* Tracking 10 */
  /* Dense (Chinese, Japanese, and Korean) */
  --typography-dense-display4-font-size: 7rem; /* Type 112sp */
  --typography-dense-display4-font-weight: 300; /* Weight Light */
  --typography-dense-display4-line-height: 7rem; /* Leading 112dp */
  --typography-dense-display4-letter-spacing: -.04em; /* Tracking -10 */
  --typography-dense-display3-font-size: 3.5rem; /* Type 56sp */
  --typography-dense-display3-font-weight: 400; /* Weight Regular */
  --typography-dense-display3-line-height: 3.5rem; /* Leading 56dp */
  --typography-dense-display3-letter-spacing: -.02em; /* Tracking -5 */
  --typography-dense-display2-font-size: 2.8125rem; /* Type 45sp */
  --typography-dense-display2-font-weight: 400; /* Weight Regular */
  --typography-dense-display2-line-height: 3.9375rem; /* Leading 63dp */
  --typography-dense-display2-letter-spacing: normal; /* Tracking 0 */
  --typography-dense-display1-font-size: 2.125rem; /* Type 34sp */
  --typography-dense-display1-font-weight: 400; /* Weight Regular */
  --typography-dense-display1-line-height: 3rem; /* Leading 48dp */
  --typography-dense-display1-letter-spacing: normal; /* Tracking 0 */
  --typography-dense-headline-font-size: 1.5rem; /* Type 24sp */
  --typography-dense-headline-font-weight: 400; /* Weight Regular */
  --typography-dense-headline-line-height: 2.125rem; /* Leading 34dp */
  --typography-dense-headline-letter-spacing: normal; /* Tracking 0 */
  --typography-dense-title-font-size: 1.3125rem; /* Type 21sp */
  --typography-dense-title-font-weight: 500; /* Weight Medium */
  --typography-dense-title-line-height: 2.125rem; /* Leading 34dp */
  --typography-dense-title-letter-spacing: .02em; /* Tracking 5 */
  --typography-dense-subheading2-font-size: 1.0625rem; /* Type 17sp (Device) and 16sp (Desktop) */
  --typography-dense-subheading2-font-weight: 400; /* Weight Regular */
  --typography-dense-subheading2-line-height: 1.875rem; /* Leading 30dp */
  --typography-dense-subheading2-letter-spacing: .04em; /* Tracking 10 */
  --typography-dense-subheading1-font-size: 1rem; /* Type 17sp (Device) and 16sp (Desktop) */
  --typography-dense-subheading1-font-weight: 400; /* Weight Regular */
  --typography-dense-subheading1-line-height: 1.625rem; /* Leading 26dp */
  --typography-dense-subheading1-letter-spacing: .04em; /* Tracking 10 */
  --typography-dense-body2-font-size: .9375rem; /* Type 15sp (Device) and 14sp (Desktop) */
  --typography-dense-body2-font-weight: 500; /* Weight Medium */
  --typography-dense-body2-line-height: 1.625rem; /* Leading 26dp */
  --typography-dense-body2-letter-spacing: .04em; /* Tracking 10 */
  --typography-dense-body1-font-size: .9375rem; /* Type 15sp (Device) and 14sp (Desktop) */
  --typography-dense-body1-font-weight: 400; /* Weight Regular */
  --typography-dense-body1-line-height: 1.4375rem; /* Leading 23dp */
  --typography-dense-body1-letter-spacing: .04em; /* Tracking 10 */
  --typography-dense-caption-font-size: .8125rem; /* Type 13sp */
  --typography-dense-caption-font-weight: 400; /* Weight Regular */
  --typography-dense-caption-line-height: 1.25rem; /* Leading 20dp */
  --typography-dense-caption-letter-spacing: .08em; /* Tracking 20 */
  --typography-dense-button-font-size: .9375rem; /* Type 15sp */
  --typography-dense-button-font-weight: 500; /* Weight Medium */
  --typography-dense-button-line-height: 2.25rem; /* Leading 36dp */
  --typography-dense-button-letter-spacing: .04em; /* Tracking 10 */
  /* Tall (South and Southeast Asian and Middle Eastern languages) */
  --typography-tall-display4-font-size: 7rem; /* Type 112sp */
  --typography-tall-display4-font-weight: 400; /* Weight Regular */
  --typography-tall-display4-line-height: 7rem; /* Leading 112dp */
  --typography-tall-display4-letter-spacing: -.04em; /* Tracking -10 */
  --typography-tall-display3-font-size: 3.5rem; /* Type 56sp */
  --typography-tall-display3-font-weight: 400; /* Weight Regular */
  --typography-tall-display3-line-height: 3.5rem; /* Leading 56dp */
  --typography-tall-display3-letter-spacing: -.02em; /* Tracking -5 */
  --typography-tall-display2-font-size: 2.8125rem; /* Type 45sp */
  --typography-tall-display2-font-weight: 400; /* Weight Regular */
  --typography-tall-display2-line-height: 3.9375rem; /* Leading 63dp */
  --typography-tall-display2-letter-spacing: normal; /* Tracking 0 */
  --typography-tall-display1-font-size: 2.125rem; /* Type 34sp */
  --typography-tall-display1-font-weight: 400; /* Weight Regular */
  --typography-tall-display1-line-height: 3rem; /* Leading 48dp */
  --typography-tall-display1-letter-spacing: normal; /* Tracking 0 */
  --typography-tall-headline-font-size: 1.5rem; /* Type 24sp */
  --typography-tall-headline-font-weight: 400; /* Weight Regular */
  --typography-tall-headline-line-height: 2.125rem; /* Leading 34dp */
  --typography-tall-headline-letter-spacing: normal; /* Tracking 0 */
  --typography-tall-title-font-size: 1.3125rem; /* Type 21sp */
  --typography-tall-title-font-weight: 700; /* Weight Bold */
  --typography-tall-title-line-height: 2.125rem; /* Leading 34dp */
  --typography-tall-title-letter-spacing: .02em; /* Tracking 5 */
  --typography-tall-subheading2-font-size: 1.0625rem; /* Type 17sp (Device) and 16sp (Desktop) */
  --typography-tall-subheading2-font-weight: 400; /* Weight Regular */
  --typography-tall-subheading2-line-height: 1.875rem; /* Leading 30dp */
  --typography-tall-subheading2-letter-spacing: .04em; /* Tracking 10 */
  --typography-tall-subheading1-font-size: 1rem; /* Type 17sp (Device) and 16sp (Desktop) */
  --typography-tall-subheading1-font-weight: 400; /* Weight Regular */
  --typography-tall-subheading1-line-height: 1.625rem; /* Leading 26dp */
  --typography-tall-subheading1-letter-spacing: .04em; /* Tracking 10 */
  --typography-tall-body2-font-size: .9375rem; /* Type 15sp (Device) and 14sp (Desktop) */
  --typography-tall-body2-font-weight: 700; /* Weight Bold */
  --typography-tall-body2-line-height: 1.625rem; /* Leading 26dp */
  --typography-tall-body2-letter-spacing: .04em; /* Tracking 10 */
  --typography-tall-body1-font-size: .9375rem; /* Type 15sp (Device) and 14sp (Desktop) */
  --typography-tall-body1-font-weight: 400; /* Weight Regular and Bold */
  --typography-tall-body1-line-height: 1.4375rem; /* Leading 23dp */
  --typography-tall-body1-letter-spacing: .04em; /* Tracking 10 */
  --typography-tall-caption-font-size: .8125rem; /* Type 13sp */
  --typography-tall-caption-font-weight: 400; /* Weight Regular */
  --typography-tall-caption-line-height: 1.25rem; /* Leading 20dp */
  --typography-tall-caption-letter-spacing: .08em; /* Tracking 20 */
  --typography-tall-button-font-size: .9375rem; /* Type 15sp */
  --typography-tall-button-font-weight: 700; /* Weight Bold */
  --typography-tall-button-line-height: 2.25rem; /* Leading 36dp */
  --typography-tall-button-letter-spacing: .04em; /* Tracking 10 */

  /* Color */
  /* Dark text on light backgrounds */
  --typography-dark-display4-color: var(--dark-secondary-text); /* Black 54% */
  --typography-dark-display3-color: var(--dark-secondary-text); /* Black 54% */
  --typography-dark-display2-color: var(--dark-secondary-text); /* Black 54% */
  --typography-dark-display1-color: var(--dark-secondary-text); /* Black 54% */
  --typography-dark-headline-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-title-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-subheading-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-body2-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-body1-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-caption-color: var(--dark-secondary-text); /* Black 54% */
  --typography-dark-menu-color: var(--dark-primary-text); /* Black 87% */
  --typography-dark-button-color: var(--dark-primary-text); /* Black 87% */
  /* White text on dark backgrounds */
  --typography-light-display4-color: var(--light-secondary-text); /* White 70% */
  --typography-light-display3-color: var(--light-secondary-text); /* White 70% */
  --typography-light-display2-color: var(--light-secondary-text); /* White 70% */
  --typography-light-display1-color: var(--light-secondary-text); /* White 70% */
  --typography-light-headline-color: var(--light-primary-text); /* White 100% */
  --typography-light-title-color: var(--light-primary-text); /* White 100% */
  --typography-light-subheading-color: var(--light-primary-text); /* White 100% */
  --typography-light-body2-color: var(--light-primary-text); /* White 100% */
  --typography-light-body1-color: var(--light-primary-text); /* White 100% */
  --typography-light-caption-color: var(--light-secondary-text); /* White 70% */
  --typography-light-menu-color: var(--light-primary-text); /* White 100% */
  --typography-light-button-color: var(--light-primary-text); /* White 100% */

}
```
